# @<COPYRIGHT>@
# ==================================================
# Copyright 2017.
# Siemens Product Lifecycle Management Software Inc.
# ==================================================
# @<COPYRIGHT>@ 

server:
  port: 4000